name-template: 'v$RESOLVED_VERSION-live'
tag-template: 'v$RESOLVED_VERSION-live'
categories:
  - title: 'Tickets'
    labels:
      - 'feature'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
exclude-labels:
  - 'skip-changelog'
autolabeler:
  - label: 'bug'
    body:
      - '/fix/'
  - label: 'feature'
    body:
      - '/BLS|STS-[0-9]{1,4}/'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES