run-name: Deploy to ${{ github.ref_name }}

on:
  push:
    branches: [ sandbox, main, develop ]
permissions:
  contents: read
env:
  NODE_ENV: ${{ github.ref_name == 'master' && 'live' || github.ref_name == 'develop' && 'dev' || github.ref_name == 'sandbox' && 'sandbox' }}
  DOTENV_NAME: ".env.${{ github.ref_name == 'master' && 'live' || github.ref_name == 'develop' && 'dev' || github.ref_name == 'sandbox' && 'sandbox' }}"


jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    environment: ${{ github.ref_name == 'master' && 'live' || github.ref_name == 'develop' && 'dev' || github.ref_name == 'sandbox' && 'sandbox' }}
    permissions:
      contents: write
      pull-requests: write
    outputs:
      api-deployment: ${{ steps.api-deployment.outputs.success }}
      db-deployment: ${{ steps.db-deployment.outputs.success }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: 'yarn'
      - name: Cache dependencies
        uses: actions/cache@v3
        id: caching-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        if: steps.caching-dependencies.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          file_name: ${{ env.DOTENV_NAME }}
          envkey_TEST: ${{ secrets.TEST_SECRET }}
          envkey_TEST_VAR: ${{ vars.TEST_VAR }}
      - name: Check variables
        run: |
          echo "1 $NODE_ENV"
          echo "2 $DOTENV_NAME"
          echo "3 ${{ secrets.TEST_SECRET }}"
          echo "4 ${{ vars.TEST_VAR }}"
      - name: Build
        id: api-deployment
        run: |
          echo "success=true" >> "$GITHUB_OUTPUT"
      - name: Deploy DB
        id: db-deployment
        run: |
          echo "success=true" >> "$GITHUB_OUTPUT"
      - name: deploy files
        id: files-deployment
        if: ${{ env.NODE_ENV }} != 'live'
        run: |
          yarn start
          echo "success=true" >> "$GITHUB_OUTPUT"

  release:
    permissions:
      contents: write
      pull-requests: write
    if: |
      always() &&
      needs.deploy.outputs.api-deployment == 'true' && needs.deploy.outputs.db-deployment == 'true'
    needs:
      - deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: 'yarn'
      - name: Cache dependencies
        uses: actions/cache@v3
        id: caching-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        if: steps.caching-dependencies.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
      - name: Check Vars
        run: |
          echo ${{ needs.deploy.outputs.api-deployment }}
          echo ${{ needs.deploy.outputs.db-deployment }}
      - name: Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



