name: Live Deployment

on:
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: |
          yarn install
          yarn --frozen-lockfile
      - name: Changelog
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy version
        run: |
          yarn deploy:version


