name: Dev Deployment

on:
  push:
    branches: sandbox
permissions:
  contents: read

env:
  NODE_ENV: sandbox

jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      api-deployment-success: ${{ steps.api-deployment }}
      db-deployment-success: ${{ steps.db-deployment }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: 'yarn'
      - name: Cache dependencies
        uses: actions/cache@v3
        id: caching-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        if: steps.caching-dependencies.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
      - name: Build
        id: api-deployment
        run: echo "Build"
      - name: Deploy DB
        id: db-deployment
        run: echo "Deploy DB"
  release:
    permissions:
      contents: write
      pull-requests: write
    if: |
      !contains(github.event.head_commit.message, 'ci skip')
    #      || (deploy.outputs.api-deployment-success == 'success' && deploy.outputs.db-deployment-success == 'success'
    needs:
      - deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: 'yarn'
      - name: Cache dependencies
        uses: actions/cache@v3
        id: caching-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        if: steps.caching-dependencies.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
      - name: Check Vars
        run: echo ${{ needs.deploy.outputs.api-deployment-success }}
      - name: Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




