name: Sync Templates Flow

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'template-changed')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync Templates
        id: sync-templates
        run: |
          # Run the Node.js script and capture the result
          SYNC_RESULT=$(yarn sync:email-templates)
          
          # Output the result as an output variable
          echo "::set-output name=sync-result::$SYNC_RESULT"

      - name: Log Sync Result
        run: |
          echo "Sync Result (before if condition): ${{ steps.sync-templates.outputs.sync-result }}"

      - name: Push Changes
        if: steps.sync-templates.outputs.sync-result == 'true'
        run: |
          git add scripts/data.json
          git commit -m "Add generated JSON data"
          git push
